path+="$HOME/.cargo/bin"
path+="$HOME/.dotnet/tools"
path+="$HOME/go/bin"
path+="$HOME/.npm-global/bin"
path+="$HOME/.local/bin"
source "$HOME/.rye/env"

export JAVA_HOME="/usr/lib/jvm/java-11-openjdk"
path+="/usr/lib/jvm/java-11-openjdk"
eval "$(rbenv init -)"
